/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Final_APUJIMA;

public class App {
  public String getGreeting() {
    return "Welcome";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
