/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Final_APUJIMA;

import org.junit.Test;

public class AppTest {
  @Test public void appHasAGreeting() {
    AppTest classUnderTest = new AppTest();
  }
}
